apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec: 
  replicas: 1
  selector: 
    matchLabels: 
       app: nginx
       project: roboshop
       component: frontend
  template: #this is the pod defination
    metadata: 
      labels:
        app: nginx
        project: roboshop
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        port: 
        - containerPort: 80

